# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='this_user',
        ),
    ]
